default:
  image: ${PROTON_CI_REGISTRY}/android-shared/docker-android/oci-ndk:v2.1.7
  tags:
    - shared-small
  before_script:
    # We must keep these variables here. We can't do it inside the entrypoint, as idk how but
    # gitlab is going to convert them as a variable content instead of a variable file...
    - mkdir -p app
    - base64 -d - < "$SERVICE_ACCOUNT_FILE" > app/service_account.json
    - base64 -d - < "$DEBUG_KEYSTORE_FILE_BASE64" > "app/$DEBUG_KEYSTORE_FILE"
    - md5sum app/service_account.json
    - git fetch origin development
    - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
    - if [ "$CI_JOB_STAGE" == "build" ]; then python3 $CI_PREPARE_TEST_ASSETS_PY; fi
  interruptible: true

variables:
  ATLAS_DEPLOY_SCOPE: $CI_PIPELINE_IID
  ATLAS_DEPLOY_LIST:
    value: fe-vpn:branch-main
    description: List of components to deploy (fe-vpn:v4.7.0:prod+t to use a tag)
  ATLAS_DEPLOY_ENV: "true"
  ATLAS_DEPLOY_PREP: "true"
  GIT_FETCH_EXTRA_FLAGS: --tags
  ORG_GRADLE_PROJECT_useCoreGitSubmodule: "false"
  NEXUS_GROUP: "/Vpn/Android/SLI/Latest/Stable"
  NEXUS_REPO: "test-productivity-builds-distribution"
  # Enable support for rebase in gitleaks_wrapper: /gitleaks/-/blob/main/docs/components-scan-repository.md
  GIT_FETCH_DEFAULT_BRANCH: "yes"
  DEBUG_KEYSTORE_FILE: "debug.keystore"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:  # Run scheduled pipelines without deploying atlas for tests.
        ATLAS_DEPLOY_ENV: "false"
        ATLAS_DEPLOY_PREP: "false"
    - if: $CI_COMMIT_BRANCH

stages:
  - prepare
  - build
  - sign
  - startReview
  - deploy
  - test
  - report
  - bot
  - mirror
  - publish
  - cleanup

# Make development and master uninterruptible.
# Based on https://gitlab.com/gitlab-org/gitlab/-/issues/194023#note_928958193
prevent-interrupt:
  stage: .pre
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "master"
  interruptible: false
  cache: []
  before_script: []
  variables:
    GIT_STRATEGY: none
  script:
    - echo "$CI_COMMIT_BRANCH is uninterruptible"

.gradle-build-cache: &gradle-build-cache
  key:
    prefix: gradle-build-cache
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - ${CI_PROJECT_DIR}/build/gradle-build-cache
  policy: pull

cache:
  - key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - .gradle

  - <<: *gradle-build-cache

deploy:review:
  needs:
    - claim:review
  after_script:
    - sleep 10
    - !reference [ .deploy:review, after_script ]
    - 'curl -s -o /dev/null --show-error -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "_method=put&mockConfig=GET+%2Fcore%2Fv4%2Fnotifications%3A%0D%0A++-+type%3A+json%0D%0A++++body%3A%0D%0A++++++Notifications%3A+%5B%5D%0D%0A" "https://${DYNAMIC_DOMAIN}/api/internal/mock"'

detekt analysis:
  stage: prepare
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull-push
      paths:
        - .gradle
  except:
    - schedules
  tags:
    - shared-large
  script:
    - ./gradlew :app:detekt
  artifacts:
    expire_in: 2 weeks
    paths:
      - app/build/reports/detekt/

# Any jobs which needs ARCHIVES_BASE_NAME should add this job as dependency
# Unless the job is building the app from gradle, then it will be calculated on it's own
export archive name:
  stage: prepare
  tags:
    - shared-large
  script:
    - export ARCHIVES_BASE_NAME=$(./gradlew -q getArchivesName | tail -n 1)
    - echo ${ARCHIVES_BASE_NAME}
    - echo "ARCHIVES_BASE_NAME=${ARCHIVES_BASE_NAME}" >> deploy.env
    - export VERSION_NAME=$(./gradlew -q getVersionName | tail -n 1)
    - echo ${VERSION_NAME}
    - echo "VERSION_NAME=${VERSION_NAME}" >> deploy.env
    - export VERSION_CODE=$(./gradlew -q getVersionCode | tail -n 1)
    - if [ $? -ne 0 ] || [ -z "${VERSION_CODE}" ]; then echo "VERSION_CODE is empty, something went wrong"; exit 1; fi
    - echo ${VERSION_CODE}
    - echo "VERSION_CODE=${VERSION_CODE}" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

build google debug:
  stage: build
  rules:
    - if: $ROBO_TEST == "true"
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  tags:
    - xlarge-k8s
  script:
    # Build additionally the vanilla and Amazon flavors to check that they compile, run lint to
    # check for use of unsupported APIs (Amazon builds have lower minSdk) and other errors.
    # Don't include them in artifacts.
    - >
      ./gradlew :app:assembleProductionGooglePlayStoreDebug \
                :app:lintProductionGooglePlayStoreDebug \
                :app:assembleProductionVanillaOpenSourceDebug \
                :app:assembleProductionVanillaAmazonDebug \
                :app:lintProductionVanillaAmazonDebug \
                :app:assembleProductionGooglePlayStoreDebugAndroidTest \
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk/productionGooglePlayStore
    - app/build/outputs/apk/androidTest/productionGooglePlayStore

.build test:
  stage: build
  tags:
    - xlarge-k8s
  except:
    - schedules
  script:
    - export BLACK_TOKEN="$(curl --silent $BLACK_TOKEN_URL)"
    - echo "API host ${TEST_ENV_DOMAIN}"
    - echo "API token ${BLACK_TOKEN}"
    - |
      if [[ "$BLACK_TOKEN" == *$'\n'* || "$BLACK_TOKEN" == *" "* ]]; then
        echo "Invalid token: ${BLACK_TOKEN}"
        exit 1
      fi
    - mkdir -p app/src/androidTest/assets/sensitive
    - cat $TEST_INTERNAL_API > app/src/androidTest/assets/sensitive/internal_apis.json
    - >
      ./gradlew :app:assembleBlackGooglePlayStoreDebug \
                  :app:assembleBlackGooglePlayStoreDebugAndroidTest
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk
    - app/build/tmp/kotlin-classes

build test-env:
  variables:
    TEST_ENV_DOMAIN: $DYNAMIC_DOMAIN
  extends: .build test

build black:
  extends: .build test
  variables:
    TEST_ENV_DOMAIN: $BLACK_DOMAIN
  after_script:
    # Avoid build files clashing with the test ones.
    - mkdir artifactsBlack
    - mv app/build/outputs/apk/* artifactsBlack
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
      - artifactsBlack

build BTI:
  stage: build
  when: manual
  except:
    - schedules
  tags:
    - xlarge-k8s
  script:
    - ./gradlew :app:assembleBlackGooglePlayStoreDebug
  after_script:
    # Avoid build files clashing with the test ones.
    - mkdir artifactsBti
    - mv app/build/outputs/apk/* artifactsBti
  artifacts:
    expire_in: 3 week
    paths:
      - artifactsBti

build google play release:
  stage: build
  when: manual
  tags:
    - xlarge-k8s
  script:
    - >
      ./gradlew openvpn:assembleRelease \
                :app:assembleProductionGooglePlayStoreRelease
  except:
    - schedules
  interruptible: false
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk

build google play dev (monitoring release):
  stage: build
  rules:
    - if: $ROBO_TEST == "true"
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  tags:
    - xlarge-k8s
  script:
    - >
      ./gradlew openvpn:assembleRelease \
                :app:assembleProductionGoogleDevRelease \
                :release_tests:assembleRelease
  interruptible: false
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/outputs/apk
      - release_tests/build/outputs/apk

unit tests:
  stage: test
  tags:
    - xlarge-k8s
  except:
    - schedules
  script:
    - ./gradlew :app:testBlackGooglePlayStoreDebugUnitTest
  artifacts:
    expire_in: 1 day
    paths:
    - app/build/test-results
    - app/build/outputs/unit_test_code_coverage
    - app/build/reports/tests

screenshot tests:
  stage: test
  tags:
    - xlarge-k8s
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
    - ./gradlew "-Duser.language=en" "-Duser.country=US" :app:validateProductionGooglePlayStoreDebugScreenshotTest
  after_script:
    - >
      if [ $CI_JOB_STATUS != 'success' ]; then
        echo -e "Screenshot tests failed!\nPlease review the report. To update the screenshots use instructions:\n${CI_PROJECT_URL}/tree/${CI_COMMIT_BRANCH}/app/src/screenshotTest/java/com/protonvpn/android"
      fi
  artifacts:
    expire_in: 1 week
    expose_as: "Screenshot Tests Report"
    when: always
    paths:
    - app/build/reports/screenshotTest/preview/debug/productionGooglePlayStore/
    - app/build/reports/screenshotTest/preview/debug/productionGooglePlayStore/index.html

coverage report:
  stage: report
  tags:
    - shared-large
  script:
    - ./gradlew coverageReport
    - python3 jacocoConverter.py app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml app/src/main/java > app/build/reports/cobertura-coverage.xml
    # create top level artifact index to direct users to the deep index
    - echo "<script>window.location='app/build/reports/jacoco/jacocoTestReport/html/index.html'</script>" > index.html
    - echo "<a href='app/build/reports/jacoco/jacocoTestReport/html/index.html'>go here</a>" >> index.html
  except:
    - schedules
  allow_failure: true
  coverage: '/Total coverage: \d+.\d+/'
  artifacts:
    expire_in: 1 week
    expose_as: 'Coverage html'
    paths:
      - app/build/reports/jacoco/jacocoTestReport/html
      - index.html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: app/build/reports/cobertura-coverage.xml

pages:
  stage: publish
  only:
    refs:
      - development
  except:
    - schedules
  script:
    - mkdir public
    - mv app/build/reports/jacoco/jacocoTestReport/html/* public
  artifacts:
    paths:
      - public

owasp check:
  stage: prepare
  tags:
    - shared-large
  script:
    - ./gradlew dependencyCheckAggregate
  when: manual
  interruptible: false
  artifacts:
    expire_in: 1 week
    paths:
      - build/reports
    reports:
      junit: build/reports/dependency-check-junit.xml

startReview:
  before_script:
    - export REVIEW_APP_ARTIFACT_PATH="app/build/outputs/apk/productionGooglePlayStore/debug/"${ARCHIVES_BASE_NAME}-production-google-playStore-debug.apk
    - echo ${REVIEW_APP_ARTIFACT_PATH}
  extends: .startReview
  needs: ["build google debug", "export archive name"]
  except:
    - schedules

stopReview:
  before_script: []
  extends: .stopReview

# See devsecops/semgrep/* components below
semgrep-scan-code:
  dependencies:
    - semgrep-customise-ruleset

include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - component: $CI_SERVER_HOST/proton/devops/cicd-components/kits/devsecops/semgrep@0.0.35

  - component: $CI_SERVER_HOST/proton/devops/cicd-components/devsecops/gitleaks/scan-repository@0.0.26
    inputs:
      configuration: ".gitleaks.toml"
      allowed-to-fail: false

  - component: $CI_SERVER_HOST/proton/devops/cicd-components/devsecops/semgrep/scan-code@0.0.20
    inputs:
      runner-tag: "shared-medium"
      configuration: "custom/semgrep/rules.yaml" # generated by customise-ruleset
      allowed-to-fail: false

  - component: $CI_SERVER_HOST/proton/devops/cicd-components/devsecops/semgrep/customise-ruleset@0.0.20
    inputs:
      cli-args: "-config .semgrep.yml"

  - component: $CI_SERVER_HOST/proton/devops/cicd-components/devsecops/grype/scan-code@0.0.22
    only: development
    inputs:
      stage: test
      cli-args: "-c .grype.yaml"

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'proton/mobile/android/proton-libs'
    ref: main
    file: '/ci/templates-shared/appetize-integration.yml'

  - local: '/.gitlab-ci-firebase.yml'

  - local: '/.gitlab-ci-release.yml'

  - project: 'proton/devops/atlas-deploy'
    ref: main
    file: '/scenarios/pipeline-env.yml'

  - project: 'proton/devops/tooling/templates'
    ref: main
    file: '/packaging/signing/artifact-signing.gitlab-ci.yml'

i18n-sync-crowdin:
  variables:
      I18N_SYNC_BRANCH: development
      I18N_SYNC_CROWDIN_PROJECT: 'android-vpn'
  extends: .i18n-sync-crowdin-shared

i18n-commit-locales:
  variables:
      I18N_COMMIT_BRANCH_PUSH: development
      I18N_COMMIT_BRANCH_ALLOWED: development
      I18N_COMMIT_CROWDIN_PROJECT: 'android-vpn'
  extends: .i18n-commit-locales-shared
